//
// Copyright (c) 2016-2020 Eclipse Microprofile Contributors:
// Red Hat
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

= Certification

The MP JWT Bridge spec would have a class of certification explicitly laid out for each of the three use cases. Each class of certification will have a distinct name and unambiguous requirements detailed in the MP JWT Bridge spec.

* **Jakarta EE Core Profile** implementations that ship **additional specs**. This class of certification caters to MP JWT implementations built on the Jakarta EE Core Profile that implement additional Jakarta EE specifications that have MP JWT Bridge spec requirements. This class of implementation would need to pass the Jakarta EE Core Profile TCK, MP JWT TCK, the corresponding Jakarta EE specifications' TCKs plus the JWT Bridge TCK tests that pertain to each of the additional Jakarta EE specs.

* **Jakarta EE Web Profile** implementations. This class of certification caters to MP JWT implementations built on the Jakarta EE Web Profile.  Implementations need to pass the Jakarta EE Web Profile TCK, MP JWT TCK, plus all requirements in the JWT Bridge spec that apply to specifications in the Jakarta EE Web Profile. Implementations in this class are not eligible to certify as a Core Profile implementation.

* **Jakarta EE Platform** implementations. This class of certification caters to MP JWT implementations built on the Jakarta EE Platform.  Implementations need to pass the Jakarta EE Platform TCK, MP JWT TCK, plus all requirements in the JWT Bridge spec that apply to specifications in the Jakarta EE Platform. Implementations in this class are not eligible to certify as a Web Profile or Core Profile implementation.

